console.log("with exception handling :")
console.log("hello");
console.log("hello");
try{
  console.log(a);
}catch{
  console.log("caught an error... a is not defined");
}
console.log("hello");
console.log("hello");
console.log("hello");

console.log("----------------------");
console.log("without exception handling :");
console.log("hello2");
console.log("hello2");
console.log(a);
console.log("hello2");
console.log("hello2");
console.log("hello2");

//handling with exceptions
